### ISSUE TITLE
Please ensure HTTP(S) and SOCKS proxies work

### ISSUE THREAD

**Issue by jirib** [SUSE/connect-ng#141]
Old SUSEConnect seems not to support SOCKS, so please ensure this works in next generation version, thank you.

A customer needed to use SOCKS5 server via SSH jumphost.

d/s BZ 1202264.

**Comment by djoreilly** [comment]
I haven't tried it, but it probably works already https://stackoverflow.com/a/49580816/17025673

**Comment by djoreilly** [comment]
It works with suseconnect-ng
```
ssh -D 1080 -N user@jumphost &
HTTPS_PROXY=socks5://127.0.0.1:1080 ./suseconnect -s
```
