### ISSUE TITLE
calling  SUSEConnect in %pre

### ISSUE THREAD

**Issue by dirkmueller** [SUSE/connect-ng#149]
There is some slightly awkward code added in the %pre script:

https://github.com/SUSE/connect-ng/commit/f18a7120910ec5f74a09c6d52c756d9337bce385#diff-5d0b38a3678dc564a97924fc379f1d16d80d594c3c895100def8f0c9f0266f84R149-R153

This should be either moved to %post, or it needs to check whether SUSEConnect is actually installed (so this is an upgrade rather than a new install). for upgrade you can check whether `[ $1 -gt 1]`.

**Comment by skazi0** [comment]
Upgrade detection is not as simple as `[ $1 -gt 1]` as we might be upgrading from old `SUSEConnect` to `suseconnect-ng` and this check would probably not work here. With the code as-is, it could check old ruby version of old ng version which is what we want.
What is the problem with this code exactly?
