### ISSUE TITLE
feature requests... "suseconnect -st" for a short version of "--status-text"

### ISSUE THREAD

**Issue by m0rbo** [SUSE/connect-ng#273]
Please add a short version for "--status-text".
"suseconnect -st" would be great!

suseconnect --status-text
Installed Products:
------------------------------------------

  SUSE Linux Enterprise Server 12 SP5
  (SLES/12.5/x86_64)

  Registered

**Comment by mssola** [comment]
We are actually thinking on doing a re-work on the CLI handling, which might lead to changes even to the user interface. This is still just a bunch of ideas, so nothing formal nor official can be shown. In the meantime, I don't think there's much value on adding short versions of existing commands.

All in all, let me close this issue, but we will definitely keep in mind this feedback whenever we finally go on to decide the new CLI handling. Thanks!
